version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: running-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    # Asegúrate de que las variables de entorno estén en el archivo .env
    environment:
      - PYTHONUNBUFFERED=1